FROM redis
MAINTAINER Blaine
#COPY /root/redis/config/redis.conf /usr/local/etc/redis/redis.conf
#COPY redis/config/redis.conf /etc/redis.conf
EXPOSE 6379
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#CMD [ "redis-server", "/etc/redis.conf" ]
CMD ["redis-server"]
